[build]
target = "index.html"
release = true
dist = "dist"
public_url = "/"
filehash = false

[watch]
watch = []
ignore = []

[serve]
address = "127.0.0.1"
port = 8080
open = false
no_autoreload = false

[clean]
dist = "dist"
cargo = false

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "gzip --keep $TRUNK_STAGING_DIR/racegate-ui_bg.wasm"]
